"""Add unique constraint to hardware serial_number

Revision ID: b0e07c87aa9b
Revises: afe02e0bd78c
Create Date: 2026-07-25 21:34:56.838608

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b0e07c87aa9b'
down_revision: Union[str, Sequence[str], None] = 'afe02e0bd78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_hardware_serial_number', ['serial_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware', schema=None) as batch_op:
        batch_op.drop_constraint('uq_hardware_serial_number', type_='unique')

    # ### end Alembic commands ###
